---
driver:
  name: terraform
  root_module_directory: ./test/fixtures/wrapper
  parallelism: 4

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: basic
      backend: aws
      attrs_outputs:
        vpc_id: vpc_id
        vpc_name: vpc_name
        security_group_ids: security_group_ids

#      controls:
#        - security_group_web_should_exist

platforms:
  - name: fedora

suites:
  - name: kt_suite